### PR TITLE
RoleAssignments GUID based on CC VM PrincipalID

### PR DESCRIPTION
**Pull request by xpillons**
not using the Resource Group ID means that we can redeploy in the same Resource Group.
The delete role script is no longer required hence the roleAssignmentCleanup.bicep. With this new method it's no longer possible to retrieve the GUID of the role once the CC VM is removed as we lose it's PrincipalID.

### CODE REVIEW

**Comment by dougclayton** [comment]
How does this affect people deploying the new bicep over an existing install to "update" it? Is that a supported use case?

**Comment by xpillons** [comment]
as new roles IDs will be created this would allow updating an existing installation. to be confirmed

**Comment by xpillons** [comment]
and confirm it failed, so need to find a better way

**Comment by abatallas** [comment]
I successfully tested the following scenarios after my initial deployment: 
* Redeploying into the same RG after deleting all initial resources
* Redeploying using the same RG name after deleting the initial RG 

I had the same results as @dougclayton when trying to update attributes of my CC installation. 

Should we consider keeping a legacy version of the delete_roles script for the users who will have clusters created prior to our next release? The new script won't properly delete their role assignments.

**Review by abatallas — APPROVED** [review]

**Pull request merged**
